# Generated by Django 4.1.2 on 2022-12-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_alter_paciente_fechanovedad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fechaNovedad',
            field=models.DateField(help_text='DD/MM/AAAA', verbose_name='Fecha de Novedad'),
        ),
    ]
