# Generated by Django 4.1.2 on 2022-12-06 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_alter_paciente_fechanovedad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='fechaNovedad',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numDocumento',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Número de Documento'),
        ),
    ]
