# Generated by Django 4.1.2 on 2022-11-22 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FechaDeDosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDeDosis', models.DateField(help_text='AAAA/MM/DD', null=True, verbose_name='Fecha para dosis')),
            ],
        ),
    ]
