# Generated by Django 4.1.2 on 2022-11-22 23:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nacionalidad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cargo', '0001_initial'),
        ('eps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDocumento', models.CharField(choices=[('C.C', 'Cédula de Ciudadanía'), ('C.E', 'Cédula de Extranjería'), ('T.I', 'Tarjeta de Identidad'), ('Otro', 'Otro tipo de Documento')], default='C.C', max_length=4, verbose_name='Tipo de Documento')),
                ('numDocumento', models.CharField(max_length=50, unique=True, verbose_name='Número de Documento')),
                ('nombres', models.CharField(max_length=60, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=60, verbose_name='Apellidos')),
                ('foto', models.ImageField(blank=True, default='images/default.png', upload_to='images/')),
                ('fecha_nacimiento', models.DateField(help_text='DD/MM/AAAA', verbose_name='Fecha de Nacimiento')),
                ('correo', models.CharField(max_length=60, unique=True, verbose_name='Correo')),
                ('celular', models.CharField(max_length=20, verbose_name='Celular')),
                ('telefono_familiar', models.CharField(max_length=20, verbose_name='Teléfono familiar')),
                ('direccion', models.CharField(max_length=70, verbose_name='Dirección')),
                ('ciudad', models.CharField(max_length=60, null=True, verbose_name='Ciudad o Municipio')),
                ('perfil', models.CharField(choices=[('admin', 'Administrador'), ('usuario', 'Usuario')], default='usuario', max_length=7, null=True, verbose_name='Perfil')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('alias', models.CharField(max_length=15, null=True, unique=True, verbose_name='Alias usuario')),
                ('fechaCreacion', models.DateField(default=datetime.date.today, null=True, verbose_name='Fecha de Creación')),
                ('cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cargo.cargo', verbose_name='Cargo')),
                ('eps', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eps.eps', verbose_name='EPS')),
                ('nacionalidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nacionalidad.nacionalidad', verbose_name='Nacionalidad')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
