# Generated by Django 4.1.2 on 2022-12-06 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_tipodocumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='alias',
            field=models.CharField(max_length=15, null=True, unique=True, verbose_name='Nombre usuario sesión'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='celular',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Número de Celular'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numDocumento',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Número de Documento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono_familiar',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Teléfono familiar'),
        ),
    ]
