# Generated by Django 4.1.2 on 2022-11-22 23:39

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0001_initial'),
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre Medicamento')),
                ('presentacion', models.CharField(choices=[('Cápsulas', 'Cápsulas'), ('Pastillas', 'Pastillas'), ('Grageas', 'Grageas'), ('Jarabe', 'Jarabe'), ('Gotas', 'Gotas'), ('Solución', 'Solución'), ('Ungüento', 'Ungüento'), ('Pomada', 'Pomada'), ('Gel', 'Gel'), ('Crema', 'Crema'), ('Vial', 'Vial'), ('Otro', 'Otro Tipo de Presentación')], default='Pastillas', max_length=80, verbose_name='Presentación')),
                ('pesoBase', models.CharField(max_length=4, verbose_name='Peso Base')),
                ('medida', models.CharField(choices=[('mcg', 'Microgramos'), ('mg', 'Miligramos'), ('g', 'Gramos'), ('ml', 'Mililitros'), ('cc', 'Centímetros Cúbicos'), ('otro', 'Otro peso')], default='mg', max_length=4, verbose_name='Medida')),
                ('stock', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock')),
                ('dosis', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Dosis a Administrar')),
                ('frecuencia', models.CharField(choices=[('1', '1 hora'), ('2', '2 horas'), ('3', '3 horas'), ('4', '4 horas'), ('6', '6 horas'), ('8', '8 horas'), ('12', '12 horas'), ('24', '24 horas'), ('Otro', 'Otra Frecuencia')], default='12', max_length=4, verbose_name='Frecuencia')),
                ('observaciones', models.TextField(max_length=250, verbose_name='Observaciones')),
                ('profesional_salud', models.CharField(max_length=50, null=True, verbose_name='Profesional que Prescribe')),
                ('consumoDiario', models.PositiveIntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Consumo Diario')),
                ('contador', models.PositiveIntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Contador')),
                ('fechaDosis', models.DateField(default=datetime.date.today, null=True, verbose_name='Fecha Dosis')),
                ('ultimaDosis', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Hora última dosis')),
                ('alerta', models.PositiveIntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Alerta')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('fechaCreacion', models.DateField(default=datetime.date.today, null=True, verbose_name='Fecha de Creación')),
                ('laboratorio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratorio.laboratorio', verbose_name='Laboratorio')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente', verbose_name='Paciente Asociado')),
            ],
        ),
    ]
