# Generated by Django 4.1.2 on 2022-12-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='frecuencia',
            field=models.CharField(choices=[('1', '1 hora'), ('2', '2 horas'), ('3', '3 horas'), ('4', '4 horas'), ('6', '6 horas'), ('8', '8 horas'), ('12', '12 horas'), ('24', '24 horas')], default='12', max_length=4, verbose_name='Frecuencia'),
        ),
    ]
