# Generated by Django 4.1.2 on 2022-12-06 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamento', '0002_alter_medicamento_frecuencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='pesoBase',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Peso Base'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='stock',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad'),
        ),
    ]
