# Generated by Django 4.1.2 on 2022-12-06 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiar', '0002_alter_familiar_tipodocumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='celular',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Número de Celular'),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='celular2',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Número de Celular Adicional'),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='numDocumento',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Número de Documento'),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='telefono_domicilio',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Teléfono domicilio'),
        ),
    ]
